### CE 103- INTRODUCTION TO COMPUTERS and PROGRAMMING

### _The topics of the week !_

- Numerical Routines **_NumPy_**
    - Array
    - Multidimensional Arrays
    - Matrix manipulations

#### List VS Array

We learned about both lists and arrays last week, _but_, what is the difference between them? When to use an array or a list in Python? Answer to these questionas are given below.

![](../Figures/array_vs_list.png)

Python has lots of data structures with different functions and features. Lists, tuples, dictionaries are some of the built-in data structures. 

So, if you have a relatively short sequence of items and you don't plan to use any mathematical operation, its better to use list, on the other hands, if you have a quite long data sequence (in same datatype) **_NumPy package_** will be very useful and highly recommended even if you plan to use mathematical operations. 

## Array in Python 

Array is a python module which defines the data structure that holds a fix number of items in same datatypes. An array stores items which called "elements" and each location of an element described by "index". "Element" and "index" are important terms to understand the concept of array. 

<p align="center">  <img src="../Figures/array_element_item.png" width = 50% > </p>

*** _image from GeeksforGeeks (https://www.geeksforgeeks.org/python-arrays/)_

To use arrays in Python, we need to import **_NumPy package_**. Because array is not a fundamental data type like strings, integer etc., we need to import the  **_NumPy package_** and declare an array. An array referred as _"ndarray"_  is shorthand for N-dimensional array which is with any number of dimension.


---
# NumPy

NumPy (Numerical Python) is an open source Python library which is very useful general-purpose array-processing package and **a core of the scientific and engineering computing ecosystem** of Python. It includes multidimensional array object, broadcasting functions, linear algebra calculations, Fourier transform and more. The NumPy library also contains matrix data structures and can be used to perform mathematical operations on arrays. NumPy can allow a wide variety of datatypes speedly. 

If you have Python you can install NumPy as below;

<font color=blue>conda install numpy<font>

,or,

<font color=blue>pip install numpy<font>

#### **How to import NumPy ?**

We prefer NumPy because it provides an enormous range of fast and efficient mathematical operations. 
Not only for NumPy but also for all packages or libraries in Python, you need to use statement **_"import"_** to make them accessible.  

In [1]:
import numpy as np

: **np** stands for an abbreviation in order to keep code standardized and make it easier to understand and faster to run. 

The command below will bring you to the reference documentation;

<font color=green>help(<font><font color=black>np.<font><font color=blue>array<font><font color=green>)<font>

In [2]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

---

### **NumPy Array**

The NumPy array can be defined as a grid of elements which can be indexed in various ways. An array in Numpy is a table of element with same type which indexed by tuple of positive integers. Tuple of integers giving the size of the array is the **_shape_** of an array. Dimensions of a NumPy array is called **_axes_**. The number of axes in array called **_rank_**. A **_vector_** is an array with a single column, a **_matrix_** is an array with multiple columns.

In [3]:
import numpy as np

a = np.array([1,2,3])  # this is a rank = 1 array

print(type(a))   # print type of the array

<class 'numpy.ndarray'>


In [4]:
print(a[1])      # indexing elements of array

2


In [5]:
print(a.dtype)   # print type of elements in array

int64


In [6]:
a = np.array([1,2,3])
print(a.shape)   # print shape of array

(3,)


#### Shape of Array
<p align="center">  <img src="../Figures/array_shape.jpg" width = 70% > </p>

*** _image from (https://blog.finxter.com/how-to-get-shape-of-array/)_

In [7]:
a = np.array([[1,2,3]])
print(a.shape)

(1, 3)


In [8]:
a = np.array([[[1,2,3]]])
print(a.shape)

(1, 1, 3)


In [9]:
a = np.array([1,2,3])
print(a.ndim)    # print number of dimensions (axes)

1


In [10]:
print(a.size)    # print size of the array (number of elements)

3


In [11]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [12]:
print(type(b[0,1]))

<class 'numpy.int64'>


---
#### **_Specify a numpy array with fuctions;_**

In [13]:
import numpy as np

a= np.zeros((3,4))     # create an array of zeros
print(a,'\n')

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 



In [14]:
b = np.ones((2,3))     # create an array of ones
print(b,'\n')

[[1. 1. 1.]
 [1. 1. 1.]] 



In [15]:
c = np.random.random((1,3))  # create an array of random numbers
print(c,'\n')

[[0.11933634 0.00966715 0.40890493]] 



In [16]:
d = np.full((3,2), 9)  # create a constant array
print(d,'\n')

[[9 9]
 [9 9]
 [9 9]] 



In [19]:
# create an identity array: a square array with ones on the main diagonal.

e = np.eye(3)       
print(e,'\n')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [21]:
# create array from a float type list (or 'str' for string type)

f = np.array([[1, 3.2, 5.6], [7, 9, 11]], dtype = 'int')  
print(f,'\n')

[[ 1  3  5]
 [ 7  9 11]] 



In [22]:
# create an array of integers upto 5
gg = np.arange(5)      
print(gg)

[0 1 2 3 4]


In [23]:
# create an array of integers between 1 to 12 with steps 2 (first #, last #, step size)

g = np.arange(1, 12, 2)  
print(g,'\n')

[ 1  3  5  7  9 11] 



In [24]:
# create an array with 4 items between 5 to 15 

h = np.linspace(5, 15, 4) 
print(h,'\n') 

[ 5.          8.33333333 11.66666667 15.        ] 



In [25]:
# create an 4x4 array with the elements of random numbers 

i = np.random.random((4,4))  
print(i)

[[0.43216356 0.86100232 0.13181478 0.94354508]
 [0.14694672 0.72176767 0.59799821 0.07856153]
 [0.25579053 0.54385061 0.68085755 0.15935576]
 [0.03712707 0.79465504 0.68504019 0.61482193]]


In [26]:
j = i.reshape(2,2,2,2)   
print(j)  

[[[[0.43216356 0.86100232]
   [0.13181478 0.94354508]]

  [[0.14694672 0.72176767]
   [0.59799821 0.07856153]]]


 [[[0.25579053 0.54385061]
   [0.68085755 0.15935576]]

  [[0.03712707 0.79465504]
   [0.68504019 0.61482193]]]]


In [27]:
j = i.reshape(4,1,4,1)   
print(j) 

[[[[0.43216356]
   [0.86100232]
   [0.13181478]
   [0.94354508]]]


 [[[0.14694672]
   [0.72176767]
   [0.59799821]
   [0.07856153]]]


 [[[0.25579053]
   [0.54385061]
   [0.68085755]
   [0.15935576]]]


 [[[0.03712707]
   [0.79465504]
   [0.68504019]
   [0.61482193]]]]


In [28]:
# give one of new shape parameter as -1 (eg: (2,-1) means that it is an unknown dimension.

k = np.array([[1, 2, 3], [4, 5, 6]])
print(k)

l = k.reshape(-1) 
print(   )
print(l)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


---
#### **_more array functions;_**


In [29]:
# Append values at the end of array
    
a = np.array([4, 2, 1, 5, 3])
print(np.append(a, [8,8]))        

[4 2 1 5 3 8 8]


In [30]:
# Inserts values into array before index 2 (array,index,values)

print(np.insert(a, 2, 55))         

[ 4  2 55  1  5  3]


In [31]:
print(np.delete(a, 3, axis = 0))   # delete row on index 3 of array


[4 2 1 3]


In [32]:
print(np.sort(a))

[1 2 3 4 5]


In [33]:
# comparison of two different array

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 1, 2])

print(a == b)

[False False False False]


In [34]:
print(a > b)

[False False  True  True]


In [35]:
# ,or, array-wise comparison can be used as below;
print(np.array_equal(a, b))

False


---
#### **_shape and resize array;_**


In [36]:
i = np.random.random([4,4])
print(i)

[[0.54145767 0.96352663 0.36254036 0.91684109]
 [0.35520918 0.60309019 0.28605518 0.17109247]
 [0.63941107 0.18942489 0.85094862 0.52606565]
 [0.06344578 0.4414825  0.65167563 0.57658474]]


In [37]:
i.ndim           # gives number of dimensions of the array 
print(i.ndim)


2


In [38]:
print(np.size(i))  # gives total number of elements of the array
np.shape(i)        # gives the shape of the array

16


(4, 4)

In [39]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

b = a.reshape(3,2) # gives a new shape to an array with same items, both arrays should have same number of elements.
print(b)

ValueError: cannot reshape array of size 8 into shape (3,2)

In [40]:
b = a.reshape(4, 2)
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


---
#### **_Array indexing;_**

Arrays can be multidimensional, we should specify a slice for each dimension, just like in list operations.

In [41]:
a = np.array([[1,3,5],[2,4,6],[7,8,9]])
print(a,'\n')

[[1 3 5]
 [2 4 6]
 [7 8 9]] 



In [42]:
b = a[:2,0:2]  # pull out the subarray of first 2 rows and columns 0 to 1
print(b,'\n')

[[1 3]
 [2 4]] 



In [43]:
print(a[1,2])  # element value at 1th row, 2nd column 

6


In [44]:
b[0,1] = 11
print(b)

[[ 1 11]
 [ 2  4]]


In [45]:
a = np.array([[1,3,5],[2,4,6],[7,8,9]])
print(a)
print()



[[1 3 5]
 [2 4 6]
 [7 8 9]]



In [46]:
row1 = a[0, :]   
print(row1)

[1 3 5]


In [47]:
row2 = a[1:2, :]
print(row2)


[[2 4 6]]


In [49]:
col1 = a[:,1]
print(col1) 

print(a)

[3 4 8]
[[1 3 5]
 [2 4 6]
 [7 8 9]]


In [50]:
col2 = a[:, 1:2]
print(col2)

[[3]
 [4]
 [8]]


In [51]:
a = np.array([[1,3,5],[2,4,6],[7,8,9]])
print(a)

[[1 3 5]
 [2 4 6]
 [7 8 9]]


In [54]:
print(a[[2, 1, 1], [0, 0, 2]])


[7 2 6]


In [55]:
print(np.array([a[0, 0], a[1, 1], a[2, 2]]))

[1 4 9]


In [72]:
a = np.array([[1,3,5],[2,4,6],[7,8,9]])


In [76]:
a[np.arange(3)] += 10
a

array([[13, 14],
       [17, 11],
       [12, 14]])

In [77]:
a = np.array([[3,4], [7, 1], [2, 4]])
bool_idx = (a > 2)
print(bool_idx) 

[[ True  True]
 [ True False]
 [False  True]]


In [78]:
print(a[bool_idx])   # print the values "true" for the condition a > 2


[3 4 7 4]


In [79]:
print(a[a > 2])

[3 4 7 4]


---
#### **_Datatypes_**

"dtype' command can be used to identify the type of an array

In [80]:
a = np.array([1,2])
print(a.dtype)         # Returns type of elements in array

int64


In [81]:
a = np.array([1.0, 2.0]) 
print(a.dtype)           

float64


In [82]:
a = np.array([1, 2], dtype=np.float64) 
print(a.dtype) 


float64


In [83]:
print(a)

[1. 2.]


In [84]:
a = np.array([1,2])
a.tolist()           # Convert array to a Python list

[1, 2]

In [85]:
np.info(np.eye)    # View documentation for "ones" properties

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

---
#### **_Basic array operations_**

_Addition, subtraction, multiplication, division, etc._

In [86]:
# Lets define two different arrays; 

data = np.random.random([1,2])
ones = np.ones(2)

print(data, ones)

[[0.84199677 0.19646026]] [1. 1.]


In [87]:
data + ones

array([[1.84199677, 1.19646026]])

In [88]:
data - ones

array([[-0.15800323, -0.80353974]])

In [89]:
data * ones

array([[0.84199677, 0.19646026]])

In [90]:
data / data

array([[1., 1.]])

In [91]:
#Operation between a vector and a scalar is allowed.

data * 2.5

array([[2.10499193, 0.49115066]])

 _Maxinum, minimum, sum, mean, product, standard deviation, etc._

In [92]:
a = np.random.random([3,])
print(a)

[0.1185819  0.7524662  0.48071726]


In [93]:
a = np.random.random([3,1])
print(a)

[[0.70590257]
 [0.10155283]
 [0.0125287 ]]


In [96]:
a = np.random.random([1,3])
print(a)

[[0.21477899 0.0075695  0.71977815]]


In [97]:
b = np.random.rand(2,3)      # 2x3 array of random floats between 0–1
print(b)

[[0.36156936 0.36185803 0.50877275]
 [0.22321719 0.1880859  0.80618163]]


In [98]:
c = np.random.rand(3,1)*100  # 3x1 array of random floats between 0–100
print(c)

[[95.29190885]
 [58.93230587]
 [29.79955822]]


In [99]:
d = np.random.randint(100, size=(3,5))    # 3x5 array with random ints between 0–100
print(d)

[[77 42 91 66 37]
 [ 2 41 19 66 39]
 [47 37 82 52 83]]


In [100]:
print(d.max())     # find the maximum value element in array


91


In [101]:
print(d.min())     # fint the minimum value element in array


2


In [102]:
print(d.sum())     # find the sum of the elements in array

781


In [103]:
# we can use arithmetic operators to do element-wise operation on array;

a = np.array([1, 2, 5, 3]) 
  
print(a + 3)     # add a scalar to each element of array 


[4 5 8 6]


In [104]:
print(a - 3)      # subtract a scalar from each element of array 


[-2 -1  2  0]


In [105]:
print(a * 2)      # multiply each element by 2 


[ 2  4 10  6]


In [106]:
print(a ** 2)     # calculate square of each element  



[ 1  4 25  9]


In [107]:
# we can also multiply array by a scalar as below;

a *= 2
print (a) # modify existing array   

[ 2  4 10  6]


In [108]:
# we can use arithmetic operators to do operation on array;
  
a = np.array([[1, 3], [5, 7]]) 
b = np.array([[2, 4], [6, 8]]) 
   
print (a + b)       # add arrays with eachother

[[ 3  7]
 [11 15]]


In [109]:
print (a * b)       # multiply arrays (elementwise multiplication)

[[ 2 12]
 [30 56]]


In [110]:
#we can also sort a NumPy array by np.sort;

a = np.array([[1, 4, 2], 
              [3, 4, 6], 
              [0, -1, 5]])

print(np.sort(a, axis = None))  # Array elements in sorted order
    


[-1  0  1  2  3  4  4  5  6]


In [111]:
print(np.sort(a, axis = 1))    # sort array row-wise

[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [112]:
# NumPy also provides mathematical functions such as sin, cos, exp, transpose etc.

a = np.array([np.pi/2, np.pi*2, 3.14]) # create an array of sine values 
print (np.cos(a)) 

[ 6.12323400e-17  1.00000000e+00 -9.99998732e-01]


In [113]:
b = np.array([1, 2, 3]) # exponential values 
print (np.exp(b)) 

[ 2.71828183  7.3890561  20.08553692]


In [114]:
print(np.sqrt(b)) # square root of array values

[1.         1.41421356 1.73205081]


In [115]:
print(np.log(b))  # logarithmic values of array elements

[0.         0.69314718 1.09861229]


In [116]:
# we can find unique element in an array

a = np.array([1, 1, 2, 3, 4, 5, 6, 7, 2, 3, 1, 4, 12, 8, 9, 0])
print(np.unique(a))


[ 0  1  2  3  4  5  6  7  8  9 12]


---
#### **_Summary of basic Matrices and Matrix Operations_**

- A matrix is a rectangular or square **_array_** of numbers which are arranged in **rows**(a set of numbers aligned horizontally in a matrix) and **columns**(a set of numbers aligned vertically in a matrix).
- Numbers of rows and columns of a matrix refer to its' **dimensions**. For example; a 2x3 (2 by 3) matrix has two rows and three columns. 
- Each number in the matrix is called **_element_**. 
- Matrices generally used in algebra to solve unknown values in **linear equations** and to solve **vector operations** in geometry.



For the matrices with same dimension, we can _add_ or _subtract_ them with each other. Also matrices may be _multiply_ with each other (when inner dimensions are the same) or any constant, as shown below.

<p class="aligncenter" >  <img src="../Figures/ce103_1.jpg" width = 50% alt="centered image"  > </p>


Multiplication process of the matrices in different dimensions are given below. Each element in the first row of matrix _A_ multiplies with each element of first column of matrix _B_, summation of them equals to the firts element of the matrix _C_. 
<p align="centre">  <img src="../Figures/ce103_3.jpg" width = 50% > </p>

To get the _Transpose_ of matrix in any dimention, we swap the rows for the columns.
<p align="centre">  <img src="../Figures/ce103_2.jpg" width = 50% > </p>

---
#### **_Matrix manipulations with Numpy;_**

In [117]:
# Lets define an array which we can manipulate matrices also;

a = np.array([[1,2],[3,4]])
print(a)


[[1 2]
 [3 4]]


In [118]:
print(a[0,1])


2


In [119]:
print(a[1::])


[[3 4]]


In [120]:
print(a[:,0])

[1 3]


In [121]:
print(a.max())     # find the maximum value element in matrix


4


In [122]:
print(a.min())     # fint the minimum value element in matrix


1


In [123]:
print(a.sum())     # find the sum of the elements in matrix

10


![](./Figures/array-sum.png)

In [124]:
print(a)


[[1 2]
 [3 4]]


In [125]:
print(a.sum(axis=0))  # column sums


[4 6]


In [126]:
print(a.sum(axis=1))  # row sums

[3 7]


In [127]:
# find maximum and minimum rows or columns of the matrix
print(a.max(axis=0))


[3 4]


In [128]:
print(a.max(axis=1))

[2 4]


In [129]:
# Two matrices at same size can be multiply or add with each other

data = np.random.random([2,3])
ones = np.ones([2,3])

print(data)

[[0.68573225 0.62813752 0.28052752]
 [0.85190805 0.35428453 0.71207299]]


In [130]:
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [131]:
a = data + ones
print(a)

[[1.68573225 1.62813752 1.28052752]
 [1.85190805 1.35428453 1.71207299]]


For matrix multiplications use the **_dot_** function to compute inner product of vector instead of **' * '** that unlike MATLAB. **_dot_** product can also be used for a vector by a matrix or matrix by matrix multiplications.

In [132]:
import numpy as np

a = np.array([2,4])
b = np.array([1,2])

print(a.dot(b))         # Inner product of vectors
print(np.dot(a, b))

10
10


In [133]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x.dot(a))         # Matrix / vector product
print(np.dot(x, a))

[10 22]
[10 22]


In [134]:
print(x.dot(y))         # Matrix / matrix product
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [135]:
# to transpose a matrix, use the T attribute of an array object:

a = np.array([[1,2], [3,4]])

print(a, '\n') 
print(a.T,'\n')   

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]] 



In [136]:
b = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
print ("\nOriginal array:\n", b) 


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]


In [137]:
print ("Transpose of array:\n", b.T) # transpose of array 

Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [138]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [139]:
a = np.arange(25).reshape(5,5)
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [140]:
print(a.diagonal())


[ 0  6 12 18 24]


In [141]:
print(a.diagonal(1))


[ 1  7 13 19]


In [ ]:
print(a.diagonal(-1))

In [ ]:
print(a.diagonal(-2))

In [142]:
a = np.array([[1,2], [3,4]])

print(np.reshape(a,[4,1]))  # shape refers to the array size or dimension size


[[1]
 [2]
 [3]
 [4]]


In [143]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

---
#### **_N-dimensional arrays_**

![](./Figures/3d-array.png)

Not only 3D, but also an array may be in 4 or more dimensional. N-dimensional arrays are widely used in Machine Learning algorithms. Here is an example of 3D NumPy array given below;

In [144]:
a = np.random.random((4,3,2))  # refers 3D array with 3 values as 4,3,2.
print(a)

[[[0.27270264 0.0098586 ]
  [0.75551634 0.44920592]
  [0.59327541 0.60907057]]

 [[0.53245869 0.30084731]
  [0.65558637 0.53471966]
  [0.52937603 0.52214327]]

 [[0.29350753 0.44562737]
  [0.91606581 0.10759066]
  [0.88659844 0.83835719]]

 [[0.69653134 0.28225369]
  [0.86691336 0.5549418 ]
  [0.67716294 0.8422181 ]]]


In [145]:
a.std()   # calculates the standart deviation of elements in array

0.24146964588747138

In [146]:
a.var()   # calculates variance of the array

0.05830758988502083

In [147]:
a.mean()   # calculates the average value of array

0.5488553762194998

In [148]:
a.cumsum()  # calculates the cumulative summation of elements in the array

array([ 0.27270264,  0.28256124,  1.03807758,  1.48728351,  2.08055891,
        2.68962948,  3.22208817,  3.52293548,  4.17852185,  4.71324151,
        5.24261753,  5.7647608 ,  6.05826833,  6.5038957 ,  7.41996151,
        7.52755217,  8.41415061,  9.2525078 ,  9.94903914, 10.23129283,
       11.09820618, 11.65314799, 12.33031093, 13.17252903])

In [149]:
a.trace(-2)  # perform a summation of each diagonal.

array([1.16042088, 1.00056918])

In [150]:
# Define matrix with complex numbers

a = np.eye(2) + 3j * np.eye(2) 
print(a)

[[1.+3.j 0.+0.j]
 [0.+0.j 1.+3.j]]


In [151]:
a.conj()    # gives the conjugate of elements of the array

array([[1.-3.j, 0.-0.j],
       [0.-0.j, 1.-3.j]])

In [152]:
a = np.array([1,2,3,4])
print(a)

np.roots(a)

[1 2 3 4]


array([-1.65062919+0.j        , -0.1746854 +1.54686889j,
       -0.1746854 -1.54686889j])

---

## Homework #3
---
Please solve the deterministic linear equation ( Ax = B ) given below by using NumPy. You can represent the problem as matrices and apply matrix algebra to solve it.

_q + r + 2p = 4_

_3q + p + 2r = 5_

_r = -23_

Formulize the problem with matrices and solve it for the vector x and print it to the screen.
Please also write a comment line before each line of your code to explain what it is for.

PS: Do not forget to upload your "HWX_namesurname.ipynb" files to http://gtuzem.gtu.edu.tr/

---